# Generated by Django 3.2 on 2021-05-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crecheapp', '0002_auto_20210421_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galerie',
            name='titre',
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.FileField(default='blog-1.jpg', upload_to='blog/image'),
        ),
    ]
