# Generated by Django 3.2 on 2021-05-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crecheapp', '0002_auto_20210421_1708'),
        ('crecheapp', '0003_auto_20210504_2232'),
    ]

    operations = [
    ]
