# Generated by Django 3.2 on 2021-07-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_activite', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('art', models.CharField(choices=[('danse', 'Danse'), ('chant', 'Chant'), ('desin', 'Desin')], max_length=20)),
                ('lecture', models.CharField(choices=[('pichou', 'Pichou'), ('dingo', 'Dingo')], max_length=20)),
                ('remarque', models.TextField()),
                ('groupe_set', models.ManyToManyField(related_name='activitygroup', to='utilisateurs.Groupe')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
            },
        ),
    ]
